Feat: auto start client + remove old angular
incentive-factory/iletaitunefoisundev pull request #234
Opened 2022-02-11 14:11 UTC by Octowire

Remove angular in makefile
Auto start with node docker

2022-02-11 14:19 UTC, TBoileau requested changes

2022-02-11 14:19 UTC, TBoileau commented on docker-compose.yml
> +    command: npm start
Attention car la première fois qu'on va build et lancer docker, ça va planter, car les dépendances gérés par npm ne seront pas installées.

2022-02-11 14:20 UTC, TBoileau commented on docker-compose.yml
> +    command: npm start
Et perso, je n'ai pas réussi à lancer un `npm install` dans le Dockerfile juste pour régler ce problème.

2022-02-11 14:21 UTC, Octowire commented on docker-compose.yml
> +    command: npm start
Ok je vois ce que tu veux dire

2022-02-11 14:25 UTC, TBoileau commented on docker-compose.yml
> +    command: npm start
et genre si on met un truc du genre :
```yaml
command: |
    npm install
    npm start
```
peut être que...

2022-02-12 01:22 UTC, Octowire commented
Finalement, le mieux reste de faire comme tu l'a déjà fait. 
Une solution avec une script sh pourrait faire l'affaire, mais je pense pas que ce soit nécessaire et apporte un réel plus

2022-02-12 01:23 UTC, closed without merging